---
title: Boris Jabes
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Boris Jabes
email: bjabes@gmail.com
markdown: kramdown
